[package]
name = "desktop"
description = "Rust Game Engine"
version = "0.1.0"
authors = ["Russell Johnson <encrypteddata0@gmail.com>", "James Sumihiro <jasumihiro@gmail.com>"]
keywords = ["game", "engine", "superdark"]
categories = ["game-engines"]
edition = "2018"

[dependencies]
super_dark_engine = { path = "../../Engine/Engine/" }